### ISSUE TITLE
I want to start a NSB persistence for apache phoenix

### ISSUE THREAD

**Issue by pablocastilla** [NServiceBusSqlPersistence/NServiceBus.SqlPersistence#11]
Hi!

I want to implement a NSB persistence for apache phoenix. I think this is the best candidate to "inspirate" my code.

What do you think?

**Comment by SimonCropp** [comment]
dont know much about apache phoenix.  can i access it through standard .ner sql connections and commands?

**Comment by pablocastilla** [comment]
Phoenix is a SQL wrapper for HBase.

I don't think I can use standard .net SQL connections, but you have encapsulated all the dataaccess. My idea is to migrate all the dataaccess from this persistence to phoenix. 

As you have connections and plain sql I suppose it will be the closest NSB persistence for me.

**Comment by SimonCropp** [comment]
ok cool. then yep this code base would be a reasonable place to start

**Comment by pablocastilla** [comment]
Thanks!
