### ISSUE TITLE
SqlVarient => SqlVariant

### ISSUE THREAD

**Issue by DavidBoike** [NServiceBusSqlPersistence/NServiceBus.SqlPersistence#5]
Spelling on the word "variant" in the API

**Comment by DavidBoike** [comment]
@SimonCropp did you just push a new package to fix this or did I accidentally get an old version somehow?

**Comment by SimonCropp** [comment]
nah i deployed a new version (with a fix from @adamralph ) a few min ago

**Comment by adamralph** [comment]
I noticed that the file in root is still called "SqlVarient.cs" but it's not used in the main solution. It might be used in Integration.sln but I couldn't get that solution to load (3 of the 4 projects fail to load).

Integration.sln also still has a few other instances of "varient" but I didn't want to try and change anything there with the solution only partially loaded (and unable to build it).

**Comment by SimonCropp** [comment]
that file is redundant. i will deleted it

> Integration.sln but I couldn't get that solution to load (3 of the 4 projects fail to load).

did u build the main solution first?

> Integration.sln also still has a few other instances of "varient" 

i cant see them??

**Comment by adamralph** [comment]
I did build the main solution first, both in Debug and Release, but Integration.sln still wouldn't load.

It looks like @SzymonPobiega fixed "varient" in Integration.sln yesterday in https://github.com/NServiceBusSqlPersistence/NServiceBus.SqlPersistence/commit/8763f2c6d0fe3774a82744abd16f97ea3a9dd4c3. Perhaps that same commit fixes the loading problem I saw.

**Comment by SzymonPobiega** [comment]
@adamralph yeah, the problem with Integration sln was due to some old paths to target files. It should be now fixed on master.
