### ISSUE TITLE
Does not remove saga data after it has completed

### ISSUE THREAD

**Issue by gromy** [NServiceBusSqlPersistence/NServiceBus.SqlPersistence#9]
I use SqlPersistance to store my saga data in MSSQL. It does not remove saga data from the db after the saga has completed. Is it a correct default behavior?

**Comment by gromy** [comment]
Sorry, it works fine when I use one endpoint instance, so it means the problem in scaling.

**Comment by SzymonPobiega** [comment]
@gromy you mean, when you have two instances marking a saga as complete does not remove the data from the database? Can you share the definition of the saga?

**Comment by gromy** [comment]
@SzymonPobiega If I launch 2 host apps(with the same endpoint) on 1 PC, it is does not remove ~50% saga data after it finished. The reason is because in my workflow the messages which define different steps of my saga can be come in incorrect order. But the strange thing that after all work is done I got 5% of all massages as error (because steps of the saga is not coordinated). Why only 5% of all messages is in error queue, and while 50% of saga is still exist... it should be approximately the same...

The code of my first example: 
3 different nodes send all events in correct order but really fast, that means actually, if I got >1 endpoints the handling of messages can be in the not correct order, but inside I got my custom state machine which forbid to complete the saga before all handlers are done their work by throwing the Exception. if the Exception is throwing the message return back to the queue. 

   ```
 [SqlSaga(correlationProperty: nameof(SagaData.CorrelationId))]
    public class MySaga : SqlSaga<SagaData>,
        IAmStartedByMessages<MyCastomEvent<MyData1>>,
        IHandleMessages<MyCastomEvent<MyData2>>,
        IHandleMessages<MyCastomEvent<MyData3>>
    {
        public UpdateAccountBalanceSaga(IWorkflowProvider provider) : base(provider)
        {
        }

        protected override void ConfigureMapping(MessagePropertyMapper<SagaData> mapper)
        {
            mapper.MapMessage<MyCastomEvent<MyData1>>(x=> x.CorrelationId);
            mapper.MapMessage<MyCastomEvent<MyData2>>(x=> x.CorrelationId);
            mapper.MapMessage<MyCastomEvent<MyData3>>(x=> x.CorrelationId);
        }

        public async Task Handle(MyCastomEvent<MyData1> myEvent, IMessageHandlerContext context)
        {
            //some work1
        }

        public async Task Handle(MyCastomEvent<MyData2> myEvent, IMessageHandlerContext context)
        {
            //some work2
        }

        public async Task Handle(MyCastomEvent<MyData3> myEvent, IMessageHandlerContext context)
        {
            //some work3 + throw Exception if work1 and work3 is not completed
            MarkAsComplete();
        }
    }
```

But, if I completely change my workflow and instead of use my custom state machine to control a correct order of handling I just will send a event like "work1 is done" and node which sent MyCastomEvent<MyData2> without any order will wait that event and sent a MyCastomEvent<MyData2> only after "work1 is done", so in this case everything is working fine.
But I do not want to handle and setup every workflow manually for every Saga.

My be I use saga wrong, but any way it should not loose the messages...
